### DISCUSSION TITLE
Package configuration when used with `substream-js`

### DISCUSSION THREAD

**Discussion by adetante** [substreams-js/substreams-js#69] [Q&A]
Hi and thanks for the work on the framework, really appreciated.

I have a question about configuring a package.
I have a custom package, composed of one module.
In the `substreams.yaml` manifest, I've declared a parameter as follows
```yaml
network: arbitrum

networks:
  arbitrum:
    params:
      map_transactions: "my-param-for-mainnet"
  arbitrum_sepolia:
    params:
      map_transactions: "my-param-for-sepolia"
```

then I initiate my stream with `substream-js` as follows
```ts
const pkg = Package.fromBinary(
  /*...*/
);
const request = createRequest({
  substreamPackage: pkg,
  outputModule: 'map_transactions',
  productionMode: true,
  startBlockNum: startBlock,
});
```

is it possible to specify the `network`, and so the configuration, that will be used by my package?
